fixed segfault in extfs fixed virt_link and ftp bug (patches from Zemljanka Commander team) use atoll in av_parse_ls so ftp can support files larger than 2GB fixed bug in ulha module updated extfs module

diff --git a/extfs/uar.in b/extfs/uar.in
--- a/extfs/uar.in
+++ b/extfs/uar.in
@@ -22,11 +22,10 @@ mcarfs_copyout ()
 
 mcarfs_copyin ()
 {
-    TMPDIR=/tmp/mctmpdir-uar.$$
-    mkdir $TMPDIR || exit 1
+    TMPDIR=`mktemp -d "${MC_TMPDIR:-/tmp}/mctmpdir-uar.XXXXXX"` || exit 1
     name=`basename "$2"`
-    (cd $TMPDIR && cp -fp "$3" $name && $XAR r "$1" $name)
-    rm -rf $TMPDIR
+    (cd "$TMPDIR" && cp -fp "$3" "$name" && $XAR r "$1" "$name")
+    rm -rf "$TMPDIR"
 }
 
 mcarfs_rm ()
@@ -44,7 +43,12 @@ case "$1" in
   copyout) shift; mcarfs_copyout "$@" ;;
   copyin) shift; mcarfs_copyin "$@" ;;
   rm) shift; mcarfs_rm "$@" ;;
-  *) exit 1;
+  mkdir|rmdir)
+    echo "mcarfs: ar archives cannot contain directories." 1>&2
+    exit 1;;
+  *)
+    echo "mcarfs: unknown command: \"$1\"." 1>&2
+    exit 1;;
 esac
 
 exit 0
