updated etxfs; some minor changes so "make distcheck" works; changed behaviour of the cache, it removes an entry from a full cache when a new entry is created and not when setting the size of an entry to prevent removal of the same entry

diff --git a/extfs/ulha.in b/extfs/ulha.in
--- a/extfs/ulha.in
+++ b/extfs/ulha.in
@@ -24,59 +24,43 @@
 # ./lha list Mystery.lha
 # to examine the output directly on the console.  The output string must be
 # precisely in the format described in the README in this directory.
-# Another helpful thing is to temporarily remove the redirection of error
-# output of awk (The '2> /dev/null' instruction near the end of mcfs_list())
-# The screen will get ugly if there's an error, but some useful text shows
-# at the bottom of the screen.  
 # Caveat emptor.
 # Learn Latin.
 
 # Define your awk
-AWK=gawk
-
-if ls -de . >& /dev/null;
-then
-    LS_COMMAND="ls -le"
-else
-    LS_COMMAND="ls -l --full-time"
-fi
+AWK=@AWK@
 
 # Define which archiver you are using with appropriate options
-LHA_LIST="lha l"
+LHA_LIST="lha lq"
 LHA_GET="lha pq"
 LHA_PUT="lha aq"
 
-# Define the temporary name of a command to be run from the archive
-TMPCMD=/tmp/mc-cmd.$$
+# Define a directory to create a temporary file for when
+# running a command to be run from the archive
+TMPDIR="/tmp/mctmpdir-uha.$$"
+# Temporary file within the directory
+TMPCMD=$TMPDIR/run
 
 # The 'list' command executive
 
 mc_lha_fs_list()
 {
-   # Get the year of the file timestamp in case we need to replace 'hh:mm'
-   YEAR=$($LS_COMMAND $1 | $AWK '{ print $10 }')
    # List the contents of the archive and sort it out    
-   $LHA_LIST $1 | $AWK -v uid=$(id -nu) -v gid=$(id -ng) -v year=$YEAR '
-      # Ignore the annotations, quit on the last one
-      /^\ PERMSSN/ { next }
-      /^-----/ { next }
-      /^\ Total/ { exit 0 }
+   $LHA_LIST "$1" | $AWK -v uid=`id -nu` -v gid=`id -ng` '
       # Strip a leading '/' if present in a filepath
       $(NF) ~ /^\// { $(NF) = substr($NF,2) }
-      # Replace the year stamp if it is expressed as 'hh:mm'
-      $(NF-1) ~ /\:/ { $(NF-1) = year }
       # Print the line this way if there is no permission string
-      $1 ~ /^\[generic\]/ {
+      $1 ~ /^\[.*\]/ {
          # Invent a generic permission
          $1 = ($10 ~ /\/$/) ? "drwxr-xr-x":"-rwxr--r--";
          # Print it
-         printf "%s   1 %-8s %-8s %-8d %3s %2d %4d %s\n",
-                 $1,     uid, gid,  $2, $4, $5, $6, $7;
+         printf "%s 1 %-8s %-8s %-8d %s %s %s %s\n",
+                 $1, uid, gid, $2, $4, $5, $6, $7;
          # Get the next line of the list
          next;
       }
       # Do it this way for a defined permission
-      $1 !~ /^\[generic\]/ {
+      $1 !~ /^\[.*\]/ {
          # If the permissions and UID run together
          if ($1 ~ /\//) {
             $8 = $7;
@@ -97,39 +81,39 @@ mc_lha_fs_list()
          # UID:GID might not be the same as on your system so print numbers
          # Well, that is the intent.  At the moment mc is translating them.
          split($2, id, "/");
-         printf "%s   1 %-8d %-8d %-8d %3s %2d %4d %s\n",
-                 $1,     id[1], id[2],  $3, $5, $6, $7, $8;
+         printf "%s 1 %-8d %-8d %-8d %s %s %s %s\n",
+                 $1, id[1], id[2], $3, $5, $6, $7, $8;
          # Get the next line of the list
          next;
       }
 
-   ' 2> /dev/null
+   ' 
 }
 
 # The 'copyout' command executive to copy displayed files to a destination
 
 mc_lha_fs_copyout()
 {
-   $LHA_GET $1 $2 > $3  2> /dev/null
+   $LHA_GET "$1" "$2" > "$3"
 }
 
 # The 'copyin' command executive to add something to the archive
 
 mc_lha_fs_copyin ()
 {
-   NAME2=`basename $2`; DIR2=${2%$NAME2}
-   NAME3=`basename $3`; DIR3=${3%$NAME3}
+   NAME2=`basename "$2"`; DIR2=${2%$NAME2}
+   NAME3=`basename "$3"`; DIR3=${3%$NAME3}
 
    cd ${DIR3}
 
    ONE2=${2%%/*}
-   [ -n ${ONE2} ] || exit
-   [ -e ${ONE2} ] && exit
+   [ -n ${ONE2} ] || exit 1
+   [ -e ${ONE2} ] && exit 1
 
    [ -e ${DIR2} ] || mkdir -p ${DIR2}
-   ln $3 $2       || exit
+   ln "$3" "$2"       || exit 1
 
-   $LHA_PUT $1 $2  2> /dev/null
+   $LHA_PUT "$1" "$2"
    rm -r ${ONE2}
 }
 
@@ -137,23 +121,28 @@ mc_lha_fs_copyin ()
 
 mc_lha_fs_run()
 {
-# FIXME: TMP RACE
-   trap "rm $TMPCMD; exit 0" 1 2 3 4 15
-   $LHA_GET $1 $2 > $TMPCMD  2> /dev/null
-   chmod a+x $TMPCMD  2> /dev/null
-   $TMPCMD 2> /dev/null
-   rm $TMPCMD
+   trap "rm -rf $TMPDIR; exit 0" 1 2 3 4 15
+   # FIXME: Try harder to generate a unique directory if this fails
+   mkdir -m 0700 $TMPDIR || exit 1
+   $LHA_GET "$1" "$2" > $TMPCMD  
+   chmod a+x $TMPCMD
+   $TMPCMD
+   rm -rf $TMPDIR
 }
 
 
 # The main routine
 umask 077
 
-case "$1" in
-   list) mc_lha_fs_list $2; exit $?;;
-   copyout) mc_lha_fs_copyout $2 $3 $4; exit $?;;
-   copyin)  mc_lha_fs_copyin  $2 $3 $4; exit $?;;
-   run)     mc_lha_fs_run     $2 $3 $4; exit $?;;
-esac
-exit 1
+cmd="$1"
+shift
 
+case "$cmd" in
+   list)    mc_lha_fs_list    "$@" ;;
+   copyout) mc_lha_fs_copyout "$@" ;;
+   copyin)  mc_lha_fs_copyin  "$@" ;;
+   run)     mc_lha_fs_run     "$@" ;;
+   *)       exit 1 ;;
+esac
+
+exit 0
